### ISSUE TITLE
Not working since upgrade to HA 2023.12

### ISSUE THREAD

**Issue by narfotic** [h4de5/home-assistant-toshiba_ac#157]
Hi,
I just upgraded to Home Assistant 2023.12 and the integration in no longer working.
It shows a notification: "Invalid config ... The following integrations and platforms could not be set up: ..."
In the logs I find:

Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 15:46:01 (3 occurrences)
Last logged: 15:47:09

Unable to install package toshiba-ac==0.3.3: ERROR: Cannot install toshiba-ac==0.3.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Logger: homeassistant.setup
Source: setup.py:221
First occurred: 15:47:09 (1 occurrences)
Last logged: 15:47:09

Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: ['toshiba-ac==0.3.3'].

**Comment by vermi0ffh** [comment]
I tried to change toshiba-ac version to 0.3.4 in manifest.json, and it seems to work well. Everything is back on track !

**Comment by gothrek22** [comment]
Yep, there is an unreleased dependency bump from the upstream KaSroka/Toshiba-AC-control, which released 0.3.4 recently. 

To workaround it, you need to find your custom_components directory, in it you have manifest.json, edit it with your editor of choice and change the string ==0.3.3 to ==0.3.4. And you're all set.

**Comment by narfotic** [comment]
Thanks for your quick response!

**Comment by infocfc** [comment]
Hi.

I have to disagree that this is fixed. I just upgraded HA to 23.12.2, and after the reboot I get exactly this error.

`2023-12-14 08:30:27.922 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package toshiba-ac==0.3.3: ERROR: Cannot install toshiba-ac==0.3.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2023-12-14 08:30:36.929 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package toshiba-ac==0.3.3: ERROR: Cannot install toshiba-ac==0.3.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2023-12-14 08:30:46.009 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package toshiba-ac==0.3.3: ERROR: Cannot install toshiba-ac==0.3.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2023-12-14 08:30:46.010 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'toshiba_ac': Requirements for toshiba_ac not found: `['toshiba-ac==0.3.3'].``

**Comment by infocfc** [comment]
> fixed in latest 2023.12 release



> Hi.
> 
> I have to disagree that this is fixed. I just upgraded HA to 23.12.2, and after the reboot I get exactly this error.

Also, changing the manifest.json to read ==0.3.4 still fixes it.
