### ISSUE TITLE
AC telling "inactive" while it's working when temperature Is as set point

### ISSUE THREAD

**Issue by h4de5** [h4de5/home-assistant-toshiba_ac#77]
> Here everything is back working with 2022.7.1. This morning wasn't.
> 
> The only thing I noticed Is AC telling "inactive" while it's working when temperature Is as set point, not working like this before

thats right. this is something that was not release before. I tested some stuff, it should return idle state, so you can check in automations for this. as the AC unit does not go into idle mode, this does not reflect reality. Ill create a new issue for this.

_Originally posted by @h4de5 in https://github.com/h4de5/home-assistant-toshiba_ac/issues/72#issuecomment-1189230469_

**Comment by dario-brombal** [comment]
It says "Inattivo", in italian can be traslated as inactive or idle. Maybe this issue Is related also to #55 ?

Anyway in past days, when turning off AC from cooling, It briefly went to off, for something like a second, then goes to cleaning, so there is actually some information about current state

**Comment by h4de5** [comment]
yes cleaning is provided as an overall flag - and its overrides the current state the unit is in. I also asked if the state can be extraced from the api and it seems it cannot. see: https://github.com/KaSroka/Toshiba-AC-control/issues/31

so this idle state will be removed again.
